alpine_task:
  container:
    image: alpine
  setup_script:
    - apk update
    - apk add build-base
  compile_script: scripts/build.sh
centos_task:
  container:
    image: centos
  setup_script:
    - yum update
    - yum install -y gcc libc-devel
  compile_script: scripts/build.sh
debian_task:
  container:
    image: debian
  setup_script:
    - apt update
    - apt install -y gcc libc-dev
  compile_script: scripts/build.sh
freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  compile_script: scripts/build.sh
macos_task:
  osx_instance:
    image: mojave-base
  compile_script: scripts/build.sh
