alpine_task:
  container:
    image: alpine
  setup_script:
    - apk update
    - apk add build-base
  compile_script: scripts/build.sh
archlinux_task:
  container:
    image: archlinux/base
  setup_script:
    - pacman --noconfirm -Sy
    - pacman --noconfirm -S gcc
  compile_script: scripts/build.sh
centos_task:
  container:
    image: centos
  setup_script:
    - yum update
    - yum install -y gcc libc-devel
  compile_script: scripts/build.sh
debian_task:
  container:
    image: debian
  setup_script:
    - apt update
    - apt install -y gcc libc-dev
  compile_script: scripts/build.sh
ubuntu_task:
  container:
    image: ubuntu
  setup_script:
    - apt update
    - apt install -y gcc libc-dev
  compile_script: scripts/build.sh
freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  compile_script: scripts/build.sh
macos_task:
  osx_instance:
    image: mojave-base
  compile_script: scripts/build.sh
cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  setup_script:
    - choco install -y --no-progress cygwin
    - c:\tools\cygwin\cygwinsetup -q -P binutils,gcc-core
  compile_script:
    - c:\tools\cygwin\bin\bash --login "%CD%\scripts\build.sh"
